db_file: "bot.db"

bot_url: "https://t.me/save_this_link_bot"

messages:
  responses:
    start: "Привет, чтобы сохранять ссылки в своем pocket аккаунте, нужно предоставить к нему доступ. Для этого переходи по ссылке:\n%s"
    already_authorized: "Ты уже авторизирован. Присылай ссылку которую нужно сохранить"
    saved_saccessfully: "Ссылка сохранена!"
    unknown_command: "Ты ввел неизвестную команду"
  errors:
    default: "Произошла неизвестная ошибка"
    invalid_url: "Ты отправил невалидную ссылку!"
    unauthorized: "Ты не автоизирован! Используй команду /start"
    unable_to_save: "Увы,не удалось сохранить ссылку. Попробуй ещё раз"