name: CI

# выполняем скрипт, когда происходит пуш в ветку main
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "bot-image"
  # CONTAINER_NAME: "bot-container"

jobs:
  build_and_push:
  # тип сервера на чем запускаетсся джоба
    runs-on: ubuntu-latest

    steps:
    # делаем пул ветки репозитория
      - name: Checkout master
        uses: actions/checkout@v2
    
    # логинимся в докерхабе
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    # создаём образ и пушим его в container registry 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bot-image:latest
